In [19]:
# pip install pillow numpy
from PIL import Image #PIL - Python Imaging Library
import numpy as np

# Function to read an image and output the data
def read_image(file_path):
    # Open the image file
    img = Image.open(file_path)
    
    # Convert the image to a NumPy array
    img_data = np.array(img)
    
    # Print basic information
    print(f"Image format: {img.format}")
    print(f"Image size: {img.size}")
    print(f"Image mode: {img.mode}") #L: This is for grayscale images. 
                    # Pixels in this mode are represented by a single value, where 0 is black and 255 is white.
    
    # Return the pixel data
    return img_data

# Specify the path to the image
file_path = '1_2_image.jpeg'

# Call the function and get image data
image_data = read_image(file_path)

# Output the image pixel data
print("Image data (pixel values):")
print(image_data)
print(image_data.shape)

Image format: JPEG
Image size: (183, 275)
Image mode: RGB
Image data (pixel values):
[[[210 224 225]
  [210 224 225]
  [210 224 225]
  ...
  [201 222 217]
  [201 222 217]
  [201 222 217]]

 [[210 224 225]
  [210 224 225]
  [210 224 225]
  ...
  [201 222 217]
  [201 222 217]
  [201 222 217]]

 [[210 224 225]
  [210 224 225]
  [210 224 225]
  ...
  [201 222 217]
  [201 222 217]
  [201 222 217]]

 ...

 [[215 229 230]
  [215 229 230]
  [214 228 229]
  ...
  [213 228 225]
  [213 228 225]
  [213 228 225]]

 [[215 229 230]
  [215 229 230]
  [214 228 229]
  ...
  [213 228 225]
  [213 228 225]
  [213 228 225]]

 [[215 229 230]
  [215 229 230]
  [214 228 229]
  ...
  [213 228 225]
  [213 228 225]
  [213 228 225]]]
(275, 183, 3)
